version: 2.0

jobs:
    build:
        docker:
            - image: felicianotech/docker-hugo:latest
        working_directory: ~/ilrw.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "aa:f7:6b:90:6d:26:60:0f:c7:d7:0b:6d:ed:f0:40:cd"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: git clone -b master git@github.com:ivanbportugal/ilrw.git docs
            - run:
                name: Generate site
                working_directory: ~/ilrw.github.io
                command: HUGO_ENV=production hugo -F -d ~/docs
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/docs
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "<YOUR_EMAIL>"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:ivanbportugal/ilrw.git master

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: source
